# Generated by Django 4.2.7 on 2025-09-22 10:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_anonymoususer_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Axtarış Vektoru'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='users_userp_search__af30f0_gin'),
        ),
    ]
