# Generated by Django 4.2.7 on 2025-09-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'order', 'name'], 'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_leaf',
            field=models.BooleanField(default=True, verbose_name='Son Kateqoriya'),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Mərhələ'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Ana Kateqoriya'),
        ),
    ]
