# Generated by Django 4.2.7 on 2025-09-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_category_options_category_is_leaf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Səhifə Sayı'),
        ),
    ]
