# Generated by Django 4.2.7 on 2025-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('az', 'Azərbaycan'), ('az_ru', 'Azərbaycan və Rus'), ('tr', 'Türk'), ('en', 'İngilis'), ('ru', 'Rus'), ('ar', 'Ərəb'), ('fa', 'Fars'), ('other', 'Digər')], default='az', max_length=10, verbose_name='Dil'),
        ),
    ]
