# Generated by Django 4.2.7 on 2025-09-22 10:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Axtarış Vektoru'),
        ),
        migrations.AddField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Axtarış Vektoru'),
        ),
        migrations.AddField(
            model_name='category',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Axtarış Vektoru'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Axtarış Vektoru'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_autho_search__69ede2_gin'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_book_search__c24b82_gin'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_categ_search__6ec0dd_gin'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_publi_search__794a5b_gin'),
        ),
    ]
