# Generated by Django 4.2.7 on 2025-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_author_search_vector_book_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_text',
            field=models.TextField(blank=True, verbose_name='Axtarış Mətni'),
        ),
    ]
