# Generated by Django 4.2.7 on 2025-09-22 10:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_delete_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Axtarış Vektoru'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='contact_con_search__c345ee_gin'),
        ),
    ]
