# Generated by Django 4.2.7 on 2025-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_sitesettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Məsələn: 40.4113084,49.9703213', max_length=50, verbose_name='Koordinatlar (lat,lng)'),
        ),
    ]
